/**
 * Human-readable names for WoW M2 animation ids.
 *
 * These are the well-known low-numbered animation slots used by most
 * models. The list is not exhaustive (there are hundreds of ids across
 * game versions) — unknown ids fall back to `Anim <id>`.
 */
const ANIMATION_NAMES: Record<number, string> = {
  0: 'Stand',
  1: 'Death',
  2: 'Spell',
  3: 'Stop',
  4: 'Walk',
  5: 'Run',
  6: 'Dead',
  7: 'Rise',
  8: 'StandWound',
  9: 'CombatWound',
  10: 'CombatCritical',
  11: 'ShuffleLeft',
  12: 'ShuffleRight',
  13: 'Walkbackwards',
  14: 'Stun',
  15: 'HandsClosed',
  16: 'AttackUnarmed',
  17: 'Attack1H',
  18: 'Attack2H',
  19: 'Attack2HL',
  20: 'ParryUnarmed',
  21: 'Parry1H',
  22: 'Parry2H',
  23: 'Parry2HL',
  24: 'ShieldBlock',
  25: 'ReadyUnarmed',
  26: 'Ready1H',
  27: 'Ready2H',
  28: 'Ready2HL',
  29: 'ReadyBow',
  30: 'Dodge',
  31: 'SpellPrecast',
  32: 'SpellCast',
  33: 'SpellCastArea',
  34: 'NPCWelcome',
  35: 'NPCGoodbye',
  36: 'Block',
  37: 'JumpStart',
  38: 'Jump',
  39: 'JumpEnd',
  40: 'Fall',
  41: 'SwimIdle',
  42: 'Swim',
  43: 'SwimLeft',
  44: 'SwimRight',
  45: 'SwimBackwards',
  46: 'AttackBow',
  47: 'FireBow',
  48: 'ReadyRifle',
  49: 'AttackRifle',
  50: 'Loot',
  60: 'EmoteTalk',
  61: 'EmoteEat',
  62: 'EmoteWork',
  63: 'EmoteUseStanding',
  64: 'EmoteTalkExclamation',
  65: 'EmoteTalkQuestion',
  66: 'EmoteBow',
  67: 'EmoteWave',
  68: 'EmoteCheer',
  69: 'EmoteDance',
  70: 'EmoteLaugh',
  71: 'EmoteSleep',
  72: 'EmoteSitGround',
  73: 'EmoteRude',
  74: 'EmoteRoar',
  75: 'EmoteKneel',
  76: 'EmoteKiss',
  77: 'EmoteCry',
  78: 'EmoteChicken',
  79: 'EmoteBeg',
  80: 'EmoteApplaud',
  81: 'EmoteShout',
  82: 'EmoteFlex',
  83: 'EmoteShy',
  84: 'EmotePoint',
  97: 'Use Standing',
  106: 'Sleep',
  107: 'SleepUp',
  108: 'SitGroundDown',
  109: 'SitGround',
  110: 'SitGroundUp',
  111: 'SleepDown',
  147: 'Fly',
  148: 'Gallop',
};

/** Return a friendly label for an animation id (with the id appended). */
export function animationName(id: number): string {
  const name = ANIMATION_NAMES[id];
  return name ? `${name} (${id})` : `Anim ${id}`;
}
